web:
  image: asp_web:latest
  links:
    - db
  command: /usr/sbin/apache2ctl -D FOREGROUND
  ports:
    - "80:80"
db:
  image: mysql:5.6.32
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: asp_magento
    MYSQL_PASSWORD: asp_magento
    MYSQL_DATABASE: magento_asp
